- name: Create directory for nginx
  file:
    path: /srv/nginx
    state: directory

- name: Create basic index.html
  copy:
    dest: /srv/nginx/index.html
    content: "<h1>Welcome from Ansible-provisioned server</h1>"

- name: Run nginx container
  community.docker.docker_container:
    name: my-nginx
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "80:80"
    volumes:
      - /srv/nginx/index.html:/usr/share/nginx/html/index.html:ro
