---
- name: Check if Docker is already installed
  command: which docker
  register: docker_installed
  ignore_errors: yes

- name: Install required system packages (prerequisites)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: yes
  when: docker_installed.rc != 0

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_installed.rc != 0

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    filename: docker
  when: docker_installed.rc != 0

- name: Update apt and install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  when: docker_installed.rc != 0

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
  when: docker_installed.rc != 0

- name: Add current user to docker group (optional)
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: docker_installed.rc != 0
